# Site settings
title: Gaemi Blog
email: segaji@gmail.com
description: |
  Gaemi 의 기술블로그입니다.
  아직 갈길이 먼 초보개발자입니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gaemi.github.io" # the base hostname & protocol for your site
twitter_username: darkGaemi
github_username:  gaemi

# Build settings

safe: true


redcarpet:
    extensions:
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap

gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  tags:
    output: true
    permalink: /tags/:path/
